language: node_js
node_js:
  - "4"

branches:
  only:
    - master

sudo: false

before_install:
  - npm install -g npm@'>=3'
  - npm --version

script:
  - npm run coverage
  # Upload to coveralls, but don't _fail_ if coveralls is down.
  - cat coverage/lcov.info | node_modules/.bin/coveralls || echo "Coveralls upload failed"
